### ISSUE TITLE
port to support python3

### ISSUE THREAD

**Issue by jprobichaud** [wujian16/Cornell-MOE#28]
Would it be possible to port to python 3?  The work seems to have been done on the original yelp/MOE depot but never reached master: https://github.com/Yelp/MOE/pull/466

**Comment by gokceneraslan** [comment]
Oh I just opened an issue here https://github.com/wujian16/Cornell-MOE/issues/27

**Comment by wujian16** [comment]
Since overlapping with #27, I close it for now.
