### ISSUE TITLE
ImportError: No module named views.constant

### ISSUE THREAD

**Issue by shalijiang** [wujian16/Cornell-MOE#40]
This is an error resulted from executing the example: python main.py Hartmann3 KG 4 1
After installation (which seems to be successful since no error was resulted, only a bunch of warnings), under moe/ there are these files: build  __init__.py  __init__.pyc  optimal_learning  tests, but no "views".
Anyone know how to fix this? Thanks

Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from moe.optimal_learning.python.cpp_wrappers.domain import TensorProductDomain as cppTensorProductDomain
  File "/home/shali/virtual_env/local/lib/python2.7/site-packages/moe/optimal_learning/python/cpp_wrappers/domain.py", line 11, in <module>
    from moe.optimal_learning.python.constant import TENSOR_PRODUCT_DOMAIN_TYPE, SIMPLEX_INTERSECT_TENSOR_PRODUCT_DOMAIN_TYPE
  File "/home/shali/virtual_env/local/lib/python2.7/site-packages/moe/optimal_learning/python/constant.py", line 6, in <module>
    import moe.views.constant as views_constant
ImportError: No module named views.constant

**Comment by wujian16** [comment]
I think that I know what causes your issue. We are cleaning up/ deleting some redundant computations in the repo. Will fix the issue soon, likely in several days. Will let you know when it’s done.

**Comment by wujian16** [comment]
I just merged a pull request to fix the problem. I tested on an AWS EC2, it worked. Please try it yourself and let me know if there are any issues.

**Comment by shalijiang** [comment]
I pulled and try that again, still have the same error.

**Comment by wujian16** [comment]
Hi,

Can you copy the error message here? Thanks!!

Because from here in the master branch

https://github.com/wujian16/Cornell-MOE/blob/master/moe/optimal_learning/python/constant.py

All the 'views' are commented now.

**Comment by shalijiang** [comment]
(virtual_env) shali@shalijiang:~/Cornell-MOE/examples$ python main.py Hartmann3 EI 4 1
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from moe.optimal_learning.python.cpp_wrappers.domain import TensorProductDomain as cppTensorProductDomain
  File "/home/shali/virtual_env/local/lib/python2.7/site-packages/moe/optimal_learning/python/cpp_wrappers/domain.py", line 11, in <module>
    from moe.optimal_learning.python.constant import TENSOR_PRODUCT_DOMAIN_TYPE, SIMPLEX_INTERSECT_TENSOR_PRODUCT_DOMAIN_TYPE
  File "/home/shali/virtual_env/local/lib/python2.7/site-packages/moe/optimal_learning/python/constant.py", line 6, in <module>
    import moe.views.constant as views_constant
ImportError: No module named views.constant

**Comment by wujian16** [comment]
I guess that it's because you need to uninstall previous versions. One way to try is that you build a new virtual environment and then install the latest master branch. 

The most recent master branch should comment out "import moe.views.constant as views_constant".

**Comment by shalijiang** [comment]
ha, ok, yes, it's working now. Thanks!

**Comment by wujian16** [comment]
great. I close the issue for now!
