### ISSUE TITLE
Analytical formula for qEI?

### ISSUE THREAD

**Issue by yangvz** [wujian16/Cornell-MOE#5]
In particular, I'm referring to the analytical formula provided by "Fast Computation of the Multi-Points Expected Improvement with Applications in Batch Selection" (Chevalier 12), the comparison to which I couldn't find in your paper, in terms of etc. speed and accuracy. It seems that for smaller values of q, it's pretty fast.

**Comment by wujian16** [comment]
The implementation of qEI can be found in
https://arxiv.org/abs/1602.05149

qEI is pretty fast at the early stages.

**Comment by yangvz** [comment]
Nice, will check it out.
