### ISSUE TITLE
errors encountered when running the examples

### ISSUE THREAD

**Issue by zullu14** [wujian16/Cornell-MOE#90]
I have followed the installation instructions strictly, tried both with python 2 and python 3,
but when it completes, I get the following error message when running the example (main.py) from the 'examples' folder:

Traceback (most recent call last):
  File "main.py", line 113, in <module>
    cpp_gp_loglikelihood.train()
  File "/home/USER/ENV_NAME/lib/python2.7/site-packages/moe/optimal_learning/python/cpp_wrappers/log_likelihood_mcmc.py", line 207, in train
    rstate0=self.rng)
  File "/home/USER/ENV_NAME/lib/python2.7/site-packages/emcee/ensemble.py", line 384, in run_mcmc
    for results in self.sample(initial_state, iterations=nsteps, **kwargs):
  File "/home/USER/ENV_NAME/lib/python2.7/site-packages/emcee/ensemble.py", line 254, in sample
    "Initial state has a large condition number. "
ValueError: Initial state has a large condition number. Make sure that your walkers are linearly independent for the best performance

I have tried several inputs with different objective functions, like: 
python main.py Branin KG 4 1
python main.py Hartmann6 KG 4 1 HeSBO 3
etc.

Has anybody encountered a similar problem?

**Comment by git163** [comment]
I have a similar problem too , any ideas on how to solve it?

**Comment by hermitdemschoenenleben** [comment]
I have the same problem and didn't find a way to solve it

**Comment by zullu14** [comment]
Apparently I have found a solution - one needs to install the older version of emcee package (https://emcee.readthedocs.io/en/stable/). I installed ver. 2.2.0 and now it is working (at least the examples are - now I will try to dig into this package).
